packages: []
catalogs:
  build:
    '@nuxt/devtools': ^2.5.0
    '@nuxt/eslint': ^1.4.1
    '@nuxt/kit': ^3.17.5
    '@nuxtjs/color-mode': ^3.5.2
    '@pinia/nuxt': ^0.11.0
    '@unocss/eslint-config': ^66.1.3
    '@unocss/nuxt': ^66.1.3
    '@vite-pwa/nuxt': ^1.0.3
    '@vueuse/nuxt': ^13.3.0
    nuxt: ^3.17.5
    unocss: ^66.1.3
    unplugin: ^2.3.5
    vite: ^6.3.5
  dev:
    '@antfu/eslint-config': ^4.13.3
    eslint: ^9.28.0
    eslint-plugin-format: ^1.0.1
    typescript: ^5.8.3
    vue-tsc: ^2.2.10
  frontend:
    '@vueuse/core': ^13.3.0
    pinia: ^3.0.2
    vue: ^3.5.16
  icons:
    '@iconify-json/carbon': ^1.2.8
    '@iconify-json/twemoji': ^1.2.2
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - unrs-resolver
